blank_issues_enabled: false
contact_links:
  - name: ECSOC 2026 Program
    url: https://github.com/SRV30/Box_Office_Inc-Movie_Sim/discussions
    about: Questions about ECSOC 2026 contribution guidelines
  - name: ELUSOC 2026 Program
    url: https://github.com/SRV30/Box_Office_Inc-Movie_Sim/discussions
    about: Questions about ELUSOC 2026 contribution guidelines
  - name: Game Discussion
    url: https://github.com/SRV30/Box_Office_Inc-Movie_Sim/discussions
    about: Ask questions and discuss game features
